/* eslint-disable */
// Generated from docs/SpecData/Mission_sheet.csv. Do not edit.
import type {MissionDef} from "./catalog";
export const GENERATED_MISSIONS: MissionDef[] = [
  {
    "id": "daily.openPack1",
    "enabled": true,
    "period": "daily",
    "event": "OpenPack",
    "target": 1,
    "title": "팩 개봉",
    "description": "카드 팩을 1회 개봉하세요",
    "passExp": 15,
    "sortOrder": 6
  },
  {
    "id": "daily.openPack3",
    "enabled": false,
    "period": "daily",
    "event": "OpenPack",
    "target": 3,
    "title": "팩 애호가",
    "description": "카드 팩을 3회 개봉하세요",
    "passExp": 0,
    "sortOrder": 2
  },
  {
    "id": "weekly.openPack10",
    "enabled": true,
    "period": "weekly",
    "event": "OpenPack",
    "target": 10,
    "title": "주간 팩 개봉",
    "description": "카드 팩을 10회 개봉하세요",
    "passExp": 30,
    "sortOrder": 3
  },
  {
    "id": "weekly.enhanceCard5",
    "enabled": false,
    "period": "weekly",
    "event": "EnhanceCard",
    "target": 5,
    "title": "주간 강화",
    "description": "카드를 5회 강화하세요",
    "passExp": 0,
    "sortOrder": 2
  },
  {
    "id": "weekly.limitBreakCard1",
    "enabled": false,
    "period": "weekly",
    "event": "LimitBreakCard",
    "target": 1,
    "title": "한계 돌파",
    "description": "카드를 1회 한계 돌파하세요",
    "passExp": 0,
    "sortOrder": 3
  },
  {
    "id": "daily.completeBattle3",
    "enabled": true,
    "period": "daily",
    "event": "CompleteBattle",
    "target": 3,
    "title": "일일 전투",
    "description": "모험과 일반 전투를 합쳐 3회 완료하세요",
    "passExp": 20,
    "sortOrder": 1
  },
  {
    "id": "weekly.winRankedBattle5",
    "enabled": false,
    "period": "weekly",
    "event": "WinRankedBattle",
    "target": 5,
    "title": "랭크 도전자",
    "description": "랭크 전투에서 5회 승리하세요",
    "passExp": 0,
    "sortOrder": 4
  },
  {
    "id": "daily.claimReward1",
    "enabled": false,
    "period": "daily",
    "event": "ClaimReward",
    "target": 1,
    "title": "보상 수령",
    "description": "보상을 1회 수령하세요",
    "passExp": 0,
    "sortOrder": 4
  },
  {
    "id": "daily.destroyCards3",
    "enabled": true,
    "period": "daily",
    "event": "DestroyCards",
    "target": 3,
    "title": "카드 파괴",
    "description": "모험과 일반 전투에서 상대 카드를 3장 파괴하세요",
    "passExp": 15,
    "sortOrder": 3
  },
  {
    "id": "daily.triggerSynergy2",
    "enabled": true,
    "period": "daily",
    "event": "TriggerSynergy",
    "target": 2,
    "title": "시너지 발동",
    "description": "모험과 일반 전투에서 시너지를 2회 발동하세요",
    "passExp": 15,
    "sortOrder": 5
  },
  {
    "id": "daily.triggerKeyword2",
    "enabled": true,
    "period": "daily",
    "event": "TriggerKeyword",
    "target": 2,
    "title": "키워드 발동",
    "description": "모험과 일반 전투에서 키워드를 2회 발동하세요",
    "passExp": 15,
    "sortOrder": 4
  },
  {
    "id": "weekly.attackTimes50",
    "enabled": false,
    "period": "weekly",
    "event": "AttackTimes",
    "target": 50,
    "title": "주간 공격",
    "description": "공격을 50회 수행하세요",
    "passExp": 0,
    "sortOrder": 5
  },
  {
    "id": "daily.completeBattle5",
    "enabled": true,
    "period": "daily",
    "event": "CompleteBattle",
    "target": 5,
    "title": "꾸준한 전투",
    "description": "모험과 일반 전투를 합쳐 5회 완료하세요",
    "passExp": 20,
    "sortOrder": 2
  },
  {
    "id": "weekly.completeBattle20",
    "enabled": true,
    "period": "weekly",
    "event": "CompleteBattle",
    "target": 20,
    "title": "주간 전투",
    "description": "모험과 일반 전투를 합쳐 20회 완료하세요",
    "passExp": 30,
    "sortOrder": 1
  },
  {
    "id": "weekly.completeBattle35",
    "enabled": true,
    "period": "weekly",
    "event": "CompleteBattle",
    "target": 35,
    "title": "끈기 있는 도전",
    "description": "모험과 일반 전투를 합쳐 35회 완료하세요",
    "passExp": 40,
    "sortOrder": 2
  },
  {
    "id": "weekly.enhanceCard10",
    "enabled": true,
    "period": "weekly",
    "event": "EnhanceCard",
    "target": 10,
    "title": "성장하는 카드",
    "description": "카드 강화를 10회 시도하세요",
    "passExp": 20,
    "sortOrder": 4
  },
  {
    "id": "weekly.winBattle10",
    "enabled": true,
    "period": "weekly",
    "event": "WinBattle",
    "target": 10,
    "title": "주간 승리",
    "description": "모험과 일반 전투를 합쳐 10회 승리하세요",
    "passExp": 40,
    "sortOrder": 5
  },
  {
    "id": "guide.01",
    "enabled": true,
    "period": "guide",
    "event": "Guide.DeckSaved6",
    "target": 1,
    "title": "내 첫 덱",
    "description": "유효한 6장 덱을 저장하세요. 기존 튜토리얼에서 저장했다면 자동 인정합니다",
    "passExp": 0,
    "sortOrder": 1
  },
  {
    "id": "guide.02",
    "enabled": true,
    "period": "guide",
    "event": "Guide.AdventureNode01",
    "target": 1,
    "title": "모험의 첫걸음",
    "description": "모험 1번 정점을 클리어하세요. 이미 클리어했다면 자동 인정합니다",
    "passExp": 0,
    "sortOrder": 2
  },
  {
    "id": "guide.03",
    "enabled": true,
    "period": "guide",
    "event": "Guide.CaretakerCardsAtStar1",
    "target": 3,
    "title": "함께 자라는 동료",
    "description": "서로 다른 돌보미 카드 3장을 1성 이상으로 성장시키세요. 이미 성장했다면 인정합니다",
    "passExp": 0,
    "sortOrder": 3
  },
  {
    "id": "guide.04",
    "enabled": true,
    "period": "guide",
    "event": "Guide.CaretakerDeckAtStar2",
    "target": 3,
    "title": "돌보미 결성",
    "description": "돌보미 카드 3장을 2성 이상으로 성장시키고 같은 덱에 편성하세요. 미리 달성해도 인정합니다",
    "passExp": 0,
    "sortOrder": 4
  },
  {
    "id": "guide.05",
    "enabled": true,
    "period": "guide",
    "event": "Guide.AdventureNode02",
    "target": 1,
    "title": "함께 싸우는 힘",
    "description": "모험 2번 정점을 클리어하세요. 돌보미 덱 사용을 권장하며 이미 클리어했다면 인정합니다",
    "passExp": 0,
    "sortOrder": 5
  },
  {
    "id": "guide.06",
    "enabled": true,
    "period": "guide",
    "event": "Guide.CaretakerTraceDeck",
    "target": 2,
    "title": "두 가지 힘",
    "description": "깜밤이와 버섯냥을 2성 이상으로 성장시키고 2성 이상 돌보미 3장과 함께 편성하세요. 미리 달성해도 인정합니다",
    "passExp": 0,
    "sortOrder": 6
  },
  {
    "id": "guide.07",
    "enabled": true,
    "period": "guide",
    "event": "Guide.AdventureNode03",
    "target": 1,
    "title": "조합으로 전진",
    "description": "모험 3번 정점을 클리어하세요. 이미 클리어했다면 자동 인정합니다",
    "passExp": 0,
    "sortOrder": 7
  },
  {
    "id": "guide.08",
    "enabled": true,
    "period": "guide",
    "event": "Guide.DeckCardsAtStar3",
    "target": 1,
    "title": "첫 번째 에이스",
    "description": "현재 덱에 3성 카드 1장을 편성하세요. 앞서 키운 2성 카드 중 선택하며 미리 달성해도 인정합니다",
    "passExp": 0,
    "sortOrder": 8
  },
  {
    "id": "guide.09",
    "enabled": true,
    "period": "guide",
    "event": "Guide.AdventureNode04",
    "target": 1,
    "title": "에이스의 첫 무대",
    "description": "모험 4번 정점을 클리어하세요. 3성 카드 사용을 권장하며 이미 클리어했다면 인정합니다",
    "passExp": 0,
    "sortOrder": 9
  },
  {
    "id": "guide.10",
    "enabled": true,
    "period": "guide",
    "event": "Guide.DeckCardsAtStar2",
    "target": 6,
    "title": "여섯 번째 자리",
    "description": "현재 덱 6장을 모두 2성 이상으로 성장시키세요. 3성 카드와 미리 달성한 상태도 인정합니다",
    "passExp": 0,
    "sortOrder": 10
  },
  {
    "id": "guide.11",
    "enabled": true,
    "period": "guide",
    "event": "Guide.AdventureNode05",
    "target": 1,
    "title": "다음 고비",
    "description": "모험 5번 정점을 클리어하세요. 이미 클리어했다면 자동 인정합니다",
    "passExp": 0,
    "sortOrder": 11
  },
  {
    "id": "guide.12",
    "enabled": true,
    "period": "guide",
    "event": "Guide.DeckCardsAtStar3",
    "target": 2,
    "title": "두 번째 에이스",
    "description": "현재 덱에 서로 다른 3성 카드 2장을 편성하세요. 미리 달성해도 인정합니다",
    "passExp": 0,
    "sortOrder": 12
  },
  {
    "id": "guide.13",
    "enabled": true,
    "period": "guide",
    "event": "Guide.AdventureChapter01",
    "target": 1,
    "title": "첫 여정 완주",
    "description": "모험 6번 정점을 클리어해 1장을 완료하세요. 이미 완료했다면 자동 인정합니다",
    "passExp": 0,
    "sortOrder": 13
  }
];
