// <auto-generated>
// SpecDataGenerator에서 만들어진 파일입니다. 수정하지 마세요.
// Copyright (c) CookApps.
// 이진호(jhlee8@cookapps.com)
// </auto-generated>

using CookApps.SpecData.Generator;


[GeneratorSpecData]
public partial class Card
{
    /// 카드 고유 번호(부여 후 변경 금지)
    [GeneratorId(nameof(id), typeof(int))]
    public int id;
    /// 에셋 이름(매칭 키)
    public string name;
    /// 화면 표시 이름
    public string displayName;
    /// Live=실행 노출 / TestOnly=테스트만
    public string channel;
    /// 기본 체력(=공격력)
    public int maxHp;
    /// 키워드(여러 개는 / 로 구분)
    public string keywords;
    /// 키워드 열리는 강화 레벨(0=처음부터)
    public int keywordUnlockLevel;
    /// SynergyData 에셋 이름(여러 개는 / 로 구분)
    public string synergies;
    /// 시작 진화 단계(0=미진화)
    public int defaultEvolutionStage;
    /// Lv2 진입 시 증가 HP
    public int hp2;
    /// Lv3 진입 시 증가 HP
    public int hp3;
    /// Lv4 진입 시 증가 HP
    public int hp4;
    /// Lv5 진입 시 증가 HP
    public int hp5;
    /// Lv6 진입 시 증가 HP
    public int hp6;
    /// Lv7 진입 시 증가 HP
    public int hp7;
    /// Lv8 진입 시 증가 HP
    public int hp8;
    /// Lv9 진입 시 증가 HP
    public int hp9;
    /// Lv10 진입 시 증가 HP
    public int hp10;
    /// 도감 설명문
    public string cardExplain;
}

[GeneratorSpecData]
public partial class Card_Test
{
    /// 카드 고유 번호(부여 후 변경 금지)
    [GeneratorId(nameof(id), typeof(int))]
    public int id;
    /// 에셋 이름(매칭 키)
    public string name;
    /// 화면 표시 이름
    public string displayName;
    /// Live=실행 노출 / TestOnly=테스트만
    public string channel;
    /// 기본 체력(=공격력)
    public int maxHp;
    /// 키워드(여러 개는 / 로 구분)
    public string keywords;
    /// 키워드 열리는 강화 레벨(0=처음부터)
    public int keywordUnlockLevel;
    /// SynergyData 에셋 이름(여러 개는 / 로 구분)
    public string synergies;
    /// 시작 진화 단계(0=미진화)
    public int defaultEvolutionStage;
    /// Lv2 진입 시 증가 HP
    public int hp2;
    /// Lv3 진입 시 증가 HP
    public int hp3;
    /// Lv4 진입 시 증가 HP
    public int hp4;
    /// Lv5 진입 시 증가 HP
    public int hp5;
    /// Lv6 진입 시 증가 HP
    public int hp6;
    /// Lv7 진입 시 증가 HP
    public int hp7;
    /// Lv8 진입 시 증가 HP
    public int hp8;
    /// Lv9 진입 시 증가 HP
    public int hp9;
    /// Lv10 진입 시 증가 HP
    public int hp10;
    /// 도감 설명문
    public string cardExplain;
    /// 카드 등급(Silver/Gold/Prism/Legendary)
    public string grade;
}

[GeneratorSpecData]
public partial class CardPack
{
    /// 팩 고유 번호(부여 후 변경 금지)
    [GeneratorId(nameof(id), typeof(int))]
    public int id;
    /// 안정 키(코드/SO 참조용
    public string packId;
    /// 변경 금지)
    public string displayName;
    /// 화면 표시 이름
    public string channel;
    /// Live=실행 노출 / TestOnly=테스트만
    public string priceType;
    /// 결제 재화(Gold/Diamond/Energy)
    public long price;
    /// 가격
    public int drawCount;
    /// 한 팩에서 뽑는 장수
    public int uniqueDraw;
    /// 1=한 팩 안 중복 없음(비복원 추출)
    public string refundType;
    /// 중복 환급 재화
    public long refundAmount;
}

[GeneratorSpecData]
public partial class CardPackDrop
{
    /// 행 고유 번호(부여 후 변경 금지)
    [GeneratorId(nameof(id), typeof(int))]
    public int id;
    /// CardPack.packId 참조
    public string packId;
    /// 이 등급 이상에서 이 묶음 사용(가장 높은 만족 등급 하나만 적용)
    public string minGrade;
    /// Card.id 참조
    public int cardId;
    /// 추첨 가중치(같은 packId+minGrade 안에서 정규화)
    public int weight;
}
