// <auto-generated>
// SpecDataGenerator에서 만들어진 파일입니다. 수정하지 마세요.
// Copyright (c) CookApps.
// 이진호(jhlee8@cookapps.com)
// </auto-generated>

using System.Linq;
using System.Security.Cryptography;
using System.Text;
using CookApps.SpecData.Generator;

[GeneratorSpecDataResource]
public static partial class SpecDataResourceLoader
{
    private static readonly byte[] _key = {99, 83, 79, 50, 98, 112, 72, 93, 76, 126, 124, 122, 98, 103, 116, 86};
}
