// <auto-generated>
// SpecDataGenerator에서 만들어진 파일입니다. 수정하지 마세요.
// Copyright (c) CookApps.
// 이진호(jhlee8@cookapps.com)
// </auto-generated>


/// 카드 키워드(비트 플래그)
[System.Flags]
public enum CARD_KEYWORD
{
    None = 0,
    Ranged = 1,
    Peerless = 2,
    Execution = 4,
    Taunt = 8,
    Cunning = 16,
    Mark = 32,
    Healer = 64,
    Invincible = 128,
    BonusHp = 256,
}

/// 카드 노출 채널
public enum CARD_CHANNEL
{
    TestOnly = 0,
    Live = 1,
}

/// 카드 등급
public enum CARD_GRADE
{
    Unknown = 0,
    Silver = 1,
    Gold = 2,
    Prism = 3,
}
