// <auto-generated>
// SpecDataGenerator에서 만들어진 파일입니다. 수정하지 마세요.
// Copyright (c) CookApps.
// 이진호(jhlee8@cookapps.com)
// </auto-generated>

using CookApps.SpecData.Generator;


[GeneratorSpecData]
public partial class Card
{
    /// 카드 고유 번호(부여 후 변경 금지)
    [GeneratorId(nameof(id), typeof(int))]
    public int id;
    /// 에셋 이름(매칭 키)
    public string name;
    /// 화면 표시 이름
    public string displayName;
    /// Live=실행 노출 / TestOnly=테스트만
    public string channel;
    /// 기본 체력(=공격력)
    public int maxHp;
    /// 키워드(여러 개는 / 로 구분)
    public string keywords;
    /// 키워드 열리는 강화 레벨(0=처음부터)
    public int keywordUnlockLevel;
    /// SynergyData 에셋 이름(여러 개는 / 로 구분)
    public string synergies;
    /// 시작 진화 단계(0=미진화)
    public int defaultEvolutionStage;
    /// Lv2 진입 시 증가 HP
    public int hp2;
    /// Lv3 진입 시 증가 HP
    public int hp3;
    /// Lv4 진입 시 증가 HP
    public int hp4;
    /// 도감 설명문
    public string cardExplain;
    /// 카드 등급(Common/Rare/Arcane/Mythic)
    public string grade;
}

[GeneratorSpecData]
public partial class CardPack
{
    /// 팩 고유 번호(부여 후 변경 금지)
    [GeneratorId(nameof(id), typeof(int))]
    public int id;
    /// 안정 키(코드 참조용, 변경 금지)
    public string packId;
    /// 화면 표시 이름
    public string displayName;
    /// Live=실행 노출 / TestOnly=테스트만
    public string channel;
    /// 결제 재화(Gold/Diamond/Energy/Shard)
    public string priceType;
    /// 가격
    public long price;
    /// 한 팩에서 뽑는 장수
    public int drawCount;
    /// 1=한 팩 안 중복 없음(비복원 추출)
    public int uniqueDraw;
    /// 중복 환급 재화
    public string refundType;
    /// 중복 1장당 환급량(0=환급 없음)
    public long refundAmount;
    /// 이 랭크 이상에서만 구매 가능(빈칸=제한 없음)
    public string minRankGrade;
    /// 상점 진열 순서(1부터. 0=진열 안 함)
    public int sortOrder;
    /// 팩 이미지 Addressables 주소(Packs 라벨)
    public string artKey;
}

[GeneratorSpecData]
public partial class CardPackDrop
{
    /// 행 고유 번호(부여 후 변경 금지)
    [GeneratorId(nameof(id), typeof(int))]
    public int id;
    /// CardPack.packId 참조
    public string packId;
    /// 이 등급 이상에서 이 묶음 사용(가장 높은 만족 등급 하나만 적용)
    public string minGrade;
    /// Card.id 참조
    public int cardId;
    /// 추첨 가중치(같은 packId+minGrade 안에서 정규화)
    public int weight;
}

[GeneratorSpecData]
public partial class RankGrade
{
    /// 행 고유 번호(부여 후 변경 금지). id 오름차순이 곧 등급 순서이고, 티어 인덱스는 이 순서에서 파생된다
    [GeneratorId(nameof(id), typeof(int))]
    public int id;
    /// 등급 키(코드 enum 이름과 1:1 · 변경 금지). Bronze/Silver/Gold/Platinum/Diamond
    public string gradeKey;
    /// 화면 표시명(단계 숫자 없이). 티어 이름은 "표시명 단계"로 조합된다
    public string displayName;
    /// 이 등급 1단계 진입 임계치. 저작 규칙: 하향만 한다 — 상향하면 임계치 아래로 내려간 기존 유저가 소급 강등된다
    public long entryPoints;
    /// 단계 간 포인트 간격 = 별 네 칸. 단계 N 임계치 = entryPoints + (N-1) * 이 값
    public long pointsPerDivision;
    /// 이 등급에서 승리 시 더할 랭크 포인트 = 별 한 칸. pointsPerDivision 을 이 값의 4배로 두면 4승에 한 단계다. 전 등급 같은 값이면 종전 동작 그대로고, 고랭크를 짜게 주려면 여기서 가른다
    public long winPoints;
    /// 이 등급에서 패배 시 뺄 랭크 포인트 = 별 한 칸. 양수로 적는다(코드가 뺀다). 승급전 한 판은 이 값을 쓰지 않는다 — 승급전은 천장/중간 지점으로 직접 쓴다
    public long losePoints;
}

[GeneratorSpecData]
public partial class AIDeck
{
    /// 행 고유 번호(부여 후 변경 금지)
    [GeneratorId(nameof(id), typeof(int))]
    public int id;
    /// 덱 안정 키
    public string deckId;
    /// 검증·로그용 이름
    public string deckName;
    /// 등장 시작 티어 인덱스
    public int fromTier;
    /// 등장 종료 티어(포함·0은 제한 없음)
    public int toTier;
    /// 같은 티어 안 등장 가중치(0 이하는 1)
    public int weight;
    /// 카드 레벨 하한(0=미저작)
    public int fromLevel;
    /// 카드 레벨 상한·포함(0=미저작)
    public int toLevel;
    /// 1번 칸 Card.id 참조
    public int card1;
    /// 2번 칸
    public int card2;
    /// 3번 칸
    public int card3;
    /// 4번 칸
    public int card4;
    /// 5번 칸
    public int card5;
    /// 6번 칸
    public int card6;
}

[GeneratorSpecData]
public partial class KeywordEnhance
{
    /// 행 고유 번호(부여 후 변경 금지)
    [GeneratorId(nameof(id), typeof(int))]
    public int id;
    /// 강화 대상 키워드(Ranged/Peerless/Execution/Taunt/Cunning/Mark/Healer/Invincible/BonusHp). 행이 없는 키워드는 강화 자체가 열리지 않는다
    public string keyword;
    /// 이 키워드의 강화 상한 레벨. 1 미만은 1로 올라간다
    public int maxLevel;
    /// 레벨 1당 더해지는 최대 체력(그 키워드를 가진 카드 전부에 붙는다). 1 미만은 1로 올라간다
    public int hpPerLevel;
    /// 1레벨 강화 비용
    public long baseCost;
    /// 레벨마다 늘어나는 비용. 레벨 N 비용 = baseCost + (N-1) * 이 값
    public long costGrowthPerLevel;
    /// 소모 재화(Gold/Diamond/Energy/Shard). 카드 강화는 조각, 키워드 강화는 에너지 축이다
    public string costCurrency;
}

[GeneratorSpecData]
public partial class Reward
{
    /// 보상 행 ID
    [GeneratorId(nameof(id), typeof(int))]
    public int id;
    /// 보상 소유 영역
    public string ownerType;
    /// 기존 수령 키
    public string ownerId;
    /// 표시 순서
    public int order;
    /// 지급물 종류
    public string rewardType;
    /// 지급물 ID
    public string rewardId;
    /// 수량
    public long amount;
}

[GeneratorSpecData]
public partial class CardEnhance
{
    /// 행 고유 번호(부여 후 변경 금지)
    [GeneratorId(nameof(id), typeof(int))]
    public int id;
    /// 대상 레벨(2 = 첫 강화). 1 이하는 강화로 도달하는 레벨이 아니라 무시된다
    public int level;
    /// 소모 재화(Gold/Diamond/Energy/Shard)
    public string costCurrency;
    /// 이 레벨업 비용. 0 이하면 무료
    public long cost;
    /// 성공률 1000분율(1000 = 100%). 범위 밖은 0~1000으로 조인다
    public int successPermille;
}

[GeneratorSpecData]
public partial class CardEnhanceRule
{
    /// 행 고유 번호(부여 후 변경 금지). 이 표는 한 줄만 쓴다 — id 1 행이 전역 설정이다
    [GeneratorId(nameof(id), typeof(int))]
    public int id;
    /// 강화 상한 레벨. 미강화가 Lv1이라 강화 횟수는 이 값 - 1이다
    public int maxLevel;
    /// 레벨업 1회 기본 체력 증가. Card 표의 hp2~hp4 가 있으면 그 값이 이긴다
    public int hpPerLevel;
    /// 첫 강화(Lv2) 기본 비용. CardEnhance 표에 그 레벨 행이 있으면 그 값이 이긴다
    public long baseEnhanceCost;
    /// 레벨마다 늘어나는 기본 비용. 레벨 N 비용 = baseEnhanceCost + (N-2) * 이 값
    public long costGrowthPerLevel;
    /// 첫 강화 기본 성공률 1000분율(1000 = 100%)
    public int baseSuccessPermille;
    /// 레벨마다 떨어지는 성공률 1000분율. 레벨 N 성공률 = baseSuccessPermille - (N-2) * 이 값
    public int rateDropPerLevelPermille;
    /// 한계돌파 최대 단계. CardLimitBreak 표는 이 단계까지만 읽힌다
    public int maxLimitBreak;
}

[GeneratorSpecData]
public partial class CardLimitBreak
{
    /// 행 고유 번호(부여 후 변경 금지)
    [GeneratorId(nameof(id), typeof(int))]
    public int id;
    /// 한계돌파 단계(1부터). CardEnhanceRule.maxLimitBreak 를 넘는 단계는 무시된다
    public int stage;
    /// 이 단계에서 더해지는 최대 체력. 누적이라 3단계 카드는 1~3단계 합을 받는다
    public int hpGain;
    /// 이 단계에 드는 간식 수(카드마다 따로 쌓이는 중복 카드 간식). 1 미만은 1로 올라간다
    public int snackCost;
}

[GeneratorSpecData]
public partial class AlbumEntry
{
    /// 행 고유 번호(부여 후 변경 금지)
    [GeneratorId(nameof(id), typeof(int))]
    public int id;
    /// AlbumTheme.themeId 참조 — 테마 안정 키
    public string themeId;
    /// 같은 테마 안에서 유일한 페이지 키
    public string pageId;
    /// Card.id 참조 — 이 칸을 채우는 카드
    public int cardId;
    /// 페이지 안 칸 순서(0부터)
    public int order;
}

[GeneratorSpecData]
public partial class AdventureChapter
{
    /// 행 고유 번호(부여 후 변경 금지)
    [GeneratorId(nameof(id), typeof(int))]
    public int id;
    /// 챕터 안정 키 — 완주 판정과 완주 보상 낙인 키
    public string chapterId;
    /// 정점 안정 키 — 클리어 낙인 키. 전체에서 유일
    public string nodeId;
    /// 챕터 안 정점 순서(0부터)
    public int order;
    /// 전역 직전 정점 — 해금 사슬. 첫 정점만 비우고 챕터 경계를 넘어 이어진다(비운 행이 둘이면 서버가 전면 차단)
    public string prevNodeId;
    /// 이 챕터에 들어갈 수 있는 rank.points 하한. 첫 등급 챕터는 0(신규 계정도 첫 등급으로 읽힌다)
    public long requiredPoints;
    /// 참고용 이름(데이터 아님)
    public string aiDeckId;
    public int aiCardLevel;
}

[GeneratorSpecData]
public partial class AlbumThemeInfo
{
    /// 행 고유 번호(부여 후 변경 금지)
    [GeneratorId(nameof(id), typeof(int))]
    public int id;
    /// 테마 안정 키 — 완성 보상 낙인 키의 뿌리. 리네임·순서 변경에도 불변
    public string themeId;
    /// 갤러리 표시 순서(0부터)
    public int order;
    /// 준비 중 테마면 1 — 갤러리에 흑백+자물쇠로만 뜨고 완성 모수에서 빠진다
    public int locked;
    /// 화면 표시 이름
    public string displayName;
    /// 셀에 한 줄로 붙는 테마 소개
    public string description;
}

[GeneratorSpecData]
public partial class SynergyDef
{
    /// 행 고유 번호(부여 후 변경 금지)
    [GeneratorId(nameof(id), typeof(int))]
    public int id;
    /// 시너지 논리 ID(코드·시트 참조용 · 변경 금지)
    public string synergyId;
    /// 화면 표시 이름
    public string displayName;
    /// 효과 설명문
    public string effectDescription;
}

[GeneratorSpecData]
public partial class SynergyEffectDef
{
    /// 행 고유 번호(부여 후 변경 금지)
    [GeneratorId(nameof(id), typeof(int))]
    public int id;
    /// SynergyDef.synergyId 참조
    public string synergyId;
    /// SynergyTierDef.tierIndex 참조
    public int tierIndex;
    /// 같은 티어 안 적용 순서(0부터)
    public int effectOrder;
    /// 효과 타입(코드 SynergyEffect 서브클래스와 1:1)
    public string effectType;
    /// 파라미터(키=값
    public string parameters;
}

[GeneratorSpecData]
public partial class SynergyTierDef
{
    /// 행 고유 번호(부여 후 변경 금지)
    [GeneratorId(nameof(id), typeof(int))]
    public int id;
    /// SynergyDef.synergyId 참조
    public string synergyId;
    /// 티어 인덱스(0부터 · 오름차순 저작)
    public int tierIndex;
    /// 열리는 최소 카드 수
    public int requiredCount;
    /// 티어 라벨(시너지 이름과 같으면 표시 생략)
    public string label;
    public string effectSummary;
}
