"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.limitBreakCard = exports.reportTournamentWin = exports.grantTutorialCards = exports.claimBattleReward = exports.enhanceKeyword = exports.enhanceCard = exports.claimPayout = exports.submitMatchResult = exports.verifyMatchTicket = exports.findAiMatch = exports.getRankSnapshot = exports.lockDeck = exports.createMatch = exports.claimReward = exports.openPack = exports.ensureWallet = exports.ensureAccount = exports.devBumpRevision = exports.ping = void 0;
var ping_1 = require("./commands/ping");
Object.defineProperty(exports, "ping", { enumerable: true, get: function () { return ping_1.ping; } });
var devBumpRevision_1 = require("./commands/devBumpRevision");
Object.defineProperty(exports, "devBumpRevision", { enumerable: true, get: function () { return devBumpRevision_1.devBumpRevision; } });
var ensureAccount_1 = require("./commands/ensureAccount");
Object.defineProperty(exports, "ensureAccount", { enumerable: true, get: function () { return ensureAccount_1.ensureAccount; } });
var ensureWallet_1 = require("./commands/ensureWallet");
Object.defineProperty(exports, "ensureWallet", { enumerable: true, get: function () { return ensureWallet_1.ensureWallet; } });
var openPack_1 = require("./commands/openPack");
Object.defineProperty(exports, "openPack", { enumerable: true, get: function () { return openPack_1.openPack; } });
var claimReward_1 = require("./commands/claimReward");
Object.defineProperty(exports, "claimReward", { enumerable: true, get: function () { return claimReward_1.claimReward; } });
var createMatch_1 = require("./commands/createMatch");
Object.defineProperty(exports, "createMatch", { enumerable: true, get: function () { return createMatch_1.createMatch; } });
var lockDeck_1 = require("./commands/lockDeck");
Object.defineProperty(exports, "lockDeck", { enumerable: true, get: function () { return lockDeck_1.lockDeck; } });
var getRankSnapshot_1 = require("./commands/getRankSnapshot");
Object.defineProperty(exports, "getRankSnapshot", { enumerable: true, get: function () { return getRankSnapshot_1.getRankSnapshot; } });
var findAiMatch_1 = require("./commands/findAiMatch");
Object.defineProperty(exports, "findAiMatch", { enumerable: true, get: function () { return findAiMatch_1.findAiMatch; } });
var verifyMatchTicket_1 = require("./commands/verifyMatchTicket");
Object.defineProperty(exports, "verifyMatchTicket", { enumerable: true, get: function () { return verifyMatchTicket_1.verifyMatchTicket; } });
var submitMatchResult_1 = require("./commands/submitMatchResult");
Object.defineProperty(exports, "submitMatchResult", { enumerable: true, get: function () { return submitMatchResult_1.submitMatchResult; } });
var claimPayout_1 = require("./commands/claimPayout");
Object.defineProperty(exports, "claimPayout", { enumerable: true, get: function () { return claimPayout_1.claimPayout; } });
var enhanceCard_1 = require("./commands/enhanceCard");
Object.defineProperty(exports, "enhanceCard", { enumerable: true, get: function () { return enhanceCard_1.enhanceCard; } });
var enhanceKeyword_1 = require("./commands/enhanceKeyword");
Object.defineProperty(exports, "enhanceKeyword", { enumerable: true, get: function () { return enhanceKeyword_1.enhanceKeyword; } });
var claimBattleReward_1 = require("./commands/claimBattleReward");
Object.defineProperty(exports, "claimBattleReward", { enumerable: true, get: function () { return claimBattleReward_1.claimBattleReward; } });
var grantTutorialCards_1 = require("./commands/grantTutorialCards");
Object.defineProperty(exports, "grantTutorialCards", { enumerable: true, get: function () { return grantTutorialCards_1.grantTutorialCards; } });
var reportTournamentWin_1 = require("./commands/reportTournamentWin");
Object.defineProperty(exports, "reportTournamentWin", { enumerable: true, get: function () { return reportTournamentWin_1.reportTournamentWin; } });
var limitBreakCard_1 = require("./commands/limitBreakCard");
Object.defineProperty(exports, "limitBreakCard", { enumerable: true, get: function () { return limitBreakCard_1.limitBreakCard; } });
//# sourceMappingURL=index.js.map