"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.getReplayDivergence = exports.claimPassRepeatReward = exports.claimPassReward = exports.getPass = exports.syncRankProfile = exports.syncGuideProgress = exports.claimMission = exports.getMissions = exports.spinRoulette = exports.limitBreakCard = exports.reportAdventureWin = exports.grantTutorialCards = exports.claimBattleReward = exports.enhanceKeyword = exports.enhanceCard = exports.claimPayout = exports.aggregateReplayDaily = exports.submitMatchResult = exports.verifyMatchTicket = exports.findAiMatch = exports.getRankLeaderboard = exports.getRankSnapshot = exports.lockDeck = exports.createMatch = exports.claimReward = exports.openPack = exports.repairSaveSlots = exports.ensureWallet = exports.ensureAccount = exports.devResetDailyMissions = exports.devCompleteMissions = exports.devResetSave = exports.devBumpRevision = exports.ping = void 0;
var ping_1 = require("./commands/ping");
Object.defineProperty(exports, "ping", { enumerable: true, get: function () { return ping_1.ping; } });
var devBumpRevision_1 = require("./commands/devBumpRevision");
Object.defineProperty(exports, "devBumpRevision", { enumerable: true, get: function () { return devBumpRevision_1.devBumpRevision; } });
var devResetSave_1 = require("./commands/devResetSave");
Object.defineProperty(exports, "devResetSave", { enumerable: true, get: function () { return devResetSave_1.devResetSave; } });
var devCompleteMissions_1 = require("./commands/devCompleteMissions");
Object.defineProperty(exports, "devCompleteMissions", { enumerable: true, get: function () { return devCompleteMissions_1.devCompleteMissions; } });
var devResetDailyMissions_1 = require("./commands/devResetDailyMissions");
Object.defineProperty(exports, "devResetDailyMissions", { enumerable: true, get: function () { return devResetDailyMissions_1.devResetDailyMissions; } });
var ensureAccount_1 = require("./commands/ensureAccount");
Object.defineProperty(exports, "ensureAccount", { enumerable: true, get: function () { return ensureAccount_1.ensureAccount; } });
var ensureWallet_1 = require("./commands/ensureWallet");
Object.defineProperty(exports, "ensureWallet", { enumerable: true, get: function () { return ensureWallet_1.ensureWallet; } });
var repairSaveSlots_1 = require("./commands/repairSaveSlots");
Object.defineProperty(exports, "repairSaveSlots", { enumerable: true, get: function () { return repairSaveSlots_1.repairSaveSlots; } });
var openPack_1 = require("./commands/openPack");
Object.defineProperty(exports, "openPack", { enumerable: true, get: function () { return openPack_1.openPack; } });
var claimReward_1 = require("./commands/claimReward");
Object.defineProperty(exports, "claimReward", { enumerable: true, get: function () { return claimReward_1.claimReward; } });
var createMatch_1 = require("./commands/createMatch");
Object.defineProperty(exports, "createMatch", { enumerable: true, get: function () { return createMatch_1.createMatch; } });
var lockDeck_1 = require("./commands/lockDeck");
Object.defineProperty(exports, "lockDeck", { enumerable: true, get: function () { return lockDeck_1.lockDeck; } });
var getRankSnapshot_1 = require("./commands/getRankSnapshot");
Object.defineProperty(exports, "getRankSnapshot", { enumerable: true, get: function () { return getRankSnapshot_1.getRankSnapshot; } });
var getRankLeaderboard_1 = require("./commands/getRankLeaderboard");
Object.defineProperty(exports, "getRankLeaderboard", { enumerable: true, get: function () { return getRankLeaderboard_1.getRankLeaderboard; } });
var findAiMatch_1 = require("./commands/findAiMatch");
Object.defineProperty(exports, "findAiMatch", { enumerable: true, get: function () { return findAiMatch_1.findAiMatch; } });
var verifyMatchTicket_1 = require("./commands/verifyMatchTicket");
Object.defineProperty(exports, "verifyMatchTicket", { enumerable: true, get: function () { return verifyMatchTicket_1.verifyMatchTicket; } });
var submitMatchResult_1 = require("./commands/submitMatchResult");
Object.defineProperty(exports, "submitMatchResult", { enumerable: true, get: function () { return submitMatchResult_1.submitMatchResult; } });
var aggregateReplayDaily_1 = require("./commands/aggregateReplayDaily");
Object.defineProperty(exports, "aggregateReplayDaily", { enumerable: true, get: function () { return aggregateReplayDaily_1.aggregateReplayDaily; } });
var claimPayout_1 = require("./commands/claimPayout");
Object.defineProperty(exports, "claimPayout", { enumerable: true, get: function () { return claimPayout_1.claimPayout; } });
var enhanceCard_1 = require("./commands/enhanceCard");
Object.defineProperty(exports, "enhanceCard", { enumerable: true, get: function () { return enhanceCard_1.enhanceCard; } });
var enhanceKeyword_1 = require("./commands/enhanceKeyword");
Object.defineProperty(exports, "enhanceKeyword", { enumerable: true, get: function () { return enhanceKeyword_1.enhanceKeyword; } });
var claimBattleReward_1 = require("./commands/claimBattleReward");
Object.defineProperty(exports, "claimBattleReward", { enumerable: true, get: function () { return claimBattleReward_1.claimBattleReward; } });
var grantTutorialCards_1 = require("./commands/grantTutorialCards");
Object.defineProperty(exports, "grantTutorialCards", { enumerable: true, get: function () { return grantTutorialCards_1.grantTutorialCards; } });
var reportAdventureWin_1 = require("./commands/reportAdventureWin");
Object.defineProperty(exports, "reportAdventureWin", { enumerable: true, get: function () { return reportAdventureWin_1.reportAdventureWin; } });
var limitBreakCard_1 = require("./commands/limitBreakCard");
Object.defineProperty(exports, "limitBreakCard", { enumerable: true, get: function () { return limitBreakCard_1.limitBreakCard; } });
var spinRoulette_1 = require("./commands/spinRoulette");
Object.defineProperty(exports, "spinRoulette", { enumerable: true, get: function () { return spinRoulette_1.spinRoulette; } });
var getMissions_1 = require("./commands/getMissions");
Object.defineProperty(exports, "getMissions", { enumerable: true, get: function () { return getMissions_1.getMissions; } });
var claimMission_1 = require("./commands/claimMission");
Object.defineProperty(exports, "claimMission", { enumerable: true, get: function () { return claimMission_1.claimMission; } });
var syncGuideProgress_1 = require("./commands/syncGuideProgress");
Object.defineProperty(exports, "syncGuideProgress", { enumerable: true, get: function () { return syncGuideProgress_1.syncGuideProgress; } });
var syncRankProfile_1 = require("./commands/syncRankProfile");
Object.defineProperty(exports, "syncRankProfile", { enumerable: true, get: function () { return syncRankProfile_1.syncRankProfile; } });
var getPass_1 = require("./commands/getPass");
Object.defineProperty(exports, "getPass", { enumerable: true, get: function () { return getPass_1.getPass; } });
var claimPassReward_1 = require("./commands/claimPassReward");
Object.defineProperty(exports, "claimPassReward", { enumerable: true, get: function () { return claimPassReward_1.claimPassReward; } });
var claimPassRepeatReward_1 = require("./commands/claimPassRepeatReward");
Object.defineProperty(exports, "claimPassRepeatReward", { enumerable: true, get: function () { return claimPassRepeatReward_1.claimPassRepeatReward; } });
var getReplayDivergence_1 = require("./commands/getReplayDivergence");
Object.defineProperty(exports, "getReplayDivergence", { enumerable: true, get: function () { return getReplayDivergence_1.getReplayDivergence; } });
//# sourceMappingURL=index.js.map